CREATE TABLE IF NOT EXISTS Consoles(
    ID INTEGER PRIMARY KEY,
    Name TEXT,
    Image TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Stations(
    ID INTEGER PRIMARY KEY,
    ConsoleID INTEGER NOT NULL,
    FOREIGN KEY(ConsoleID) REFERENCES Consoles(ID)
);

CREATE TABLE IF NOT EXISTS Controllers(
    ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Image TEXT,
    Count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ConsoleControllers(
    ID INTEGER PRIMARY KEY,
    ConsoleID INTEGER NOT NULL,
    ControllerID INTEGER NOT NULL,

    FOREIGN KEY(ConsoleID) REFERENCES Consoles(ID),
    FOREIGN KEY(ControllerID) REFERENCES Controllers(ID)
);


CREATE TABLE IF NOT EXISTS Games(
    ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    ConsoleID INTEGER NOT NULL,
    Count INTEGER NOT NULL,

    FOREIGN KEY(ConsoleID) REFERENCES Consoles(ID)
);

CREATE TABLE IF NOT EXISTS Barcodes(
    ID INTEGER PRIMARY KEY,
    GameID INTEGER NOT NULL,
    Barcode TEXT NOT NULL,

    FOREIGN KEY(GameID) REFERENCES Games(ID)
);

CREATE TABLE IF NOT EXISTS Rentals(
    ID INTEGER PRIMARY KEY,
    BadgeID INTEGER NOT NULL,
    ControllerID INTEGER NOT NULL,
    GameID INTEGER NOT NULL,

    FOREIGN KEY(GameID) REFERENCES Games(ID),
    FOREIGN KEY(ControllerID) REFERENCES Controllers(ID)
);

CREATE TABLE IF NOT EXISTS Transactions(
    ID INTEGER PRIMARY KEY,
    Type TEXT NOT NULL,
    BadgeID INTEGER NOT NULL,
    StationID INTEGER NOT NULL,
    GameID INTEGER NOT NULL,
    ControllerID INTEGER NOT NULL,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
